config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'

  resources :articles, except: [:destroy]

  root controller: :articles, action: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :author, presence: true

  has_many :comment
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to @article
  end

  private

  def article_params
      params[:article].permit(:title, :content, :author)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    if @comment.persisted?
      flash[:success] = "Made comment"
      redirect_back(fallback_location: root_path)
    else
      flash[:success] = "Your comment was not created"
      redirect_back(fallback_location: root_path)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:email, :body, :article_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
  </tr>

  <% @articles.each do |article| %>
      <p><%= link_to article.title, article_path(article)%></p>
      <p><%= article.content %></p>
      <p><%= link_to 'Show', article_path(article) %></p>
  <% end %>
</table>

<h1><a href ='/articles/new'>new article</a></h1>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>

  <p>
    <%= form.label :author %><br>
    <%= form.text_area :author%>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<%= form_with model: Comment.new, local: true do |form| %>
  <%= form.label :email %>
  <%= form.email_field :email %>
  <%= form.label :body, value: 'Comment' %>
  <%= form.text_field :body %>
  <%= form.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.keys.each do |type| %>
      <%= flash[type] %>
    <% end %>
    <%= yield %>
  </body>
</html>